/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletToolsRouteImport } from './routes/_authenticated/wallet-tools'
import { Route as AuthenticatedVipRouteImport } from './routes/_authenticated/vip'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCmsThemeRouteImport } from './routes/_authenticated/cms-theme'
import { Route as AuthenticatedCmsMusicRouteImport } from './routes/_authenticated/cms-music'
import { Route as AuthenticatedCmsGamesRouteImport } from './routes/_authenticated/cms-games'
import { Route as AuthenticatedCashoutsRouteImport } from './routes/_authenticated/cashouts'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as ApiPublicOutboundIpRouteImport } from './routes/api/public/outbound-ip'
import { Route as ApiMetaWebhookRouteImport } from './routes/api/meta/webhook'
import { Route as ApiSupportAttachmentMessageIdRouteImport } from './routes/api/support/attachment.$messageId'
import { Route as ApiPublicJuwaWithdrawRouteImport } from './routes/api/public/juwa/withdraw'
import { Route as ApiPublicJuwaResetPasswordRouteImport } from './routes/api/public/juwa/reset-password'
import { Route as ApiPublicJuwaRechargeRouteImport } from './routes/api/public/juwa/recharge'
import { Route as ApiPublicJuwaCreatePlayerRouteImport } from './routes/api/public/juwa/create-player'
import { Route as ApiPublicJuwaBalanceRouteImport } from './routes/api/public/juwa/balance'
import { Route as ApiPublicChatStartRouteImport } from './routes/api/public/chat/start'
import { Route as ApiPublicChatMessageRouteImport } from './routes/api/public/chat/message'
import { Route as ApiPublicChatConfigRouteImport } from './routes/api/public/chat/config'
import { Route as ApiPublicChatTicketIdMessagesRouteImport } from './routes/api/public/chat/ticket.$id.messages'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletToolsRoute =
  AuthenticatedWalletToolsRouteImport.update({
    id: '/wallet-tools',
    path: '/wallet-tools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipRoute = AuthenticatedVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsThemeRoute = AuthenticatedCmsThemeRouteImport.update({
  id: '/cms-theme',
  path: '/cms-theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsMusicRoute = AuthenticatedCmsMusicRouteImport.update({
  id: '/cms-music',
  path: '/cms-music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsGamesRoute = AuthenticatedCmsGamesRouteImport.update({
  id: '/cms-games',
  path: '/cms-games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashoutsRoute = AuthenticatedCashoutsRouteImport.update({
  id: '/cashouts',
  path: '/cashouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOutboundIpRoute = ApiPublicOutboundIpRouteImport.update({
  id: '/api/public/outbound-ip',
  path: '/api/public/outbound-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaWebhookRoute = ApiMetaWebhookRouteImport.update({
  id: '/api/meta/webhook',
  path: '/api/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportAttachmentMessageIdRoute =
  ApiSupportAttachmentMessageIdRouteImport.update({
    id: '/api/support/attachment/$messageId',
    path: '/api/support/attachment/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJuwaWithdrawRoute = ApiPublicJuwaWithdrawRouteImport.update({
  id: '/api/public/juwa/withdraw',
  path: '/api/public/juwa/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJuwaResetPasswordRoute =
  ApiPublicJuwaResetPasswordRouteImport.update({
    id: '/api/public/juwa/reset-password',
    path: '/api/public/juwa/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJuwaRechargeRoute = ApiPublicJuwaRechargeRouteImport.update({
  id: '/api/public/juwa/recharge',
  path: '/api/public/juwa/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJuwaCreatePlayerRoute =
  ApiPublicJuwaCreatePlayerRouteImport.update({
    id: '/api/public/juwa/create-player',
    path: '/api/public/juwa/create-player',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJuwaBalanceRoute = ApiPublicJuwaBalanceRouteImport.update({
  id: '/api/public/juwa/balance',
  path: '/api/public/juwa/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatStartRoute = ApiPublicChatStartRouteImport.update({
  id: '/api/public/chat/start',
  path: '/api/public/chat/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatMessageRoute = ApiPublicChatMessageRouteImport.update({
  id: '/api/public/chat/message',
  path: '/api/public/chat/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatConfigRoute = ApiPublicChatConfigRouteImport.update({
  id: '/api/public/chat/config',
  path: '/api/public/chat/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatTicketIdMessagesRoute =
  ApiPublicChatTicketIdMessagesRouteImport.update({
    id: '/api/public/chat/ticket/$id/messages',
    path: '/api/public/chat/ticket/$id/messages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/cashouts': typeof AuthenticatedCashoutsRoute
  '/cms-games': typeof AuthenticatedCmsGamesRoute
  '/cms-music': typeof AuthenticatedCmsMusicRoute
  '/cms-theme': typeof AuthenticatedCmsThemeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/support': typeof AuthenticatedSupportRoute
  '/system': typeof AuthenticatedSystemRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vip': typeof AuthenticatedVipRoute
  '/wallet-tools': typeof AuthenticatedWalletToolsRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/outbound-ip': typeof ApiPublicOutboundIpRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/start': typeof ApiPublicChatStartRoute
  '/api/public/juwa/balance': typeof ApiPublicJuwaBalanceRoute
  '/api/public/juwa/create-player': typeof ApiPublicJuwaCreatePlayerRoute
  '/api/public/juwa/recharge': typeof ApiPublicJuwaRechargeRoute
  '/api/public/juwa/reset-password': typeof ApiPublicJuwaResetPasswordRoute
  '/api/public/juwa/withdraw': typeof ApiPublicJuwaWithdrawRoute
  '/api/support/attachment/$messageId': typeof ApiSupportAttachmentMessageIdRoute
  '/api/public/chat/ticket/$id/messages': typeof ApiPublicChatTicketIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/cashouts': typeof AuthenticatedCashoutsRoute
  '/cms-games': typeof AuthenticatedCmsGamesRoute
  '/cms-music': typeof AuthenticatedCmsMusicRoute
  '/cms-theme': typeof AuthenticatedCmsThemeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/support': typeof AuthenticatedSupportRoute
  '/system': typeof AuthenticatedSystemRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vip': typeof AuthenticatedVipRoute
  '/wallet-tools': typeof AuthenticatedWalletToolsRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/outbound-ip': typeof ApiPublicOutboundIpRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/start': typeof ApiPublicChatStartRoute
  '/api/public/juwa/balance': typeof ApiPublicJuwaBalanceRoute
  '/api/public/juwa/create-player': typeof ApiPublicJuwaCreatePlayerRoute
  '/api/public/juwa/recharge': typeof ApiPublicJuwaRechargeRoute
  '/api/public/juwa/reset-password': typeof ApiPublicJuwaResetPasswordRoute
  '/api/public/juwa/withdraw': typeof ApiPublicJuwaWithdrawRoute
  '/api/support/attachment/$messageId': typeof ApiSupportAttachmentMessageIdRoute
  '/api/public/chat/ticket/$id/messages': typeof ApiPublicChatTicketIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/cashouts': typeof AuthenticatedCashoutsRoute
  '/_authenticated/cms-games': typeof AuthenticatedCmsGamesRoute
  '/_authenticated/cms-music': typeof AuthenticatedCmsMusicRoute
  '/_authenticated/cms-theme': typeof AuthenticatedCmsThemeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/vip': typeof AuthenticatedVipRoute
  '/_authenticated/wallet-tools': typeof AuthenticatedWalletToolsRoute
  '/api/meta/webhook': typeof ApiMetaWebhookRoute
  '/api/public/outbound-ip': typeof ApiPublicOutboundIpRoute
  '/api/public/chat/config': typeof ApiPublicChatConfigRoute
  '/api/public/chat/message': typeof ApiPublicChatMessageRoute
  '/api/public/chat/start': typeof ApiPublicChatStartRoute
  '/api/public/juwa/balance': typeof ApiPublicJuwaBalanceRoute
  '/api/public/juwa/create-player': typeof ApiPublicJuwaCreatePlayerRoute
  '/api/public/juwa/recharge': typeof ApiPublicJuwaRechargeRoute
  '/api/public/juwa/reset-password': typeof ApiPublicJuwaResetPasswordRoute
  '/api/public/juwa/withdraw': typeof ApiPublicJuwaWithdrawRoute
  '/api/support/attachment/$messageId': typeof ApiSupportAttachmentMessageIdRoute
  '/api/public/chat/ticket/$id/messages': typeof ApiPublicChatTicketIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/announcements'
    | '/audit-log'
    | '/backups'
    | '/cashouts'
    | '/cms-games'
    | '/cms-music'
    | '/cms-theme'
    | '/dashboard'
    | '/deposits'
    | '/notifications'
    | '/payment-methods'
    | '/payments'
    | '/payouts'
    | '/platforms'
    | '/players'
    | '/promotions'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/staff'
    | '/support'
    | '/system'
    | '/transactions'
    | '/vip'
    | '/wallet-tools'
    | '/api/meta/webhook'
    | '/api/public/outbound-ip'
    | '/api/public/chat/config'
    | '/api/public/chat/message'
    | '/api/public/chat/start'
    | '/api/public/juwa/balance'
    | '/api/public/juwa/create-player'
    | '/api/public/juwa/recharge'
    | '/api/public/juwa/reset-password'
    | '/api/public/juwa/withdraw'
    | '/api/support/attachment/$messageId'
    | '/api/public/chat/ticket/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/announcements'
    | '/audit-log'
    | '/backups'
    | '/cashouts'
    | '/cms-games'
    | '/cms-music'
    | '/cms-theme'
    | '/dashboard'
    | '/deposits'
    | '/notifications'
    | '/payment-methods'
    | '/payments'
    | '/payouts'
    | '/platforms'
    | '/players'
    | '/promotions'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/staff'
    | '/support'
    | '/system'
    | '/transactions'
    | '/vip'
    | '/wallet-tools'
    | '/api/meta/webhook'
    | '/api/public/outbound-ip'
    | '/api/public/chat/config'
    | '/api/public/chat/message'
    | '/api/public/chat/start'
    | '/api/public/juwa/balance'
    | '/api/public/juwa/create-player'
    | '/api/public/juwa/recharge'
    | '/api/public/juwa/reset-password'
    | '/api/public/juwa/withdraw'
    | '/api/support/attachment/$messageId'
    | '/api/public/chat/ticket/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/announcements'
    | '/_authenticated/audit-log'
    | '/_authenticated/backups'
    | '/_authenticated/cashouts'
    | '/_authenticated/cms-games'
    | '/_authenticated/cms-music'
    | '/_authenticated/cms-theme'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposits'
    | '/_authenticated/notifications'
    | '/_authenticated/payment-methods'
    | '/_authenticated/payments'
    | '/_authenticated/payouts'
    | '/_authenticated/platforms'
    | '/_authenticated/players'
    | '/_authenticated/promotions'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/support'
    | '/_authenticated/system'
    | '/_authenticated/transactions'
    | '/_authenticated/vip'
    | '/_authenticated/wallet-tools'
    | '/api/meta/webhook'
    | '/api/public/outbound-ip'
    | '/api/public/chat/config'
    | '/api/public/chat/message'
    | '/api/public/chat/start'
    | '/api/public/juwa/balance'
    | '/api/public/juwa/create-player'
    | '/api/public/juwa/recharge'
    | '/api/public/juwa/reset-password'
    | '/api/public/juwa/withdraw'
    | '/api/support/attachment/$messageId'
    | '/api/public/chat/ticket/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMetaWebhookRoute: typeof ApiMetaWebhookRoute
  ApiPublicOutboundIpRoute: typeof ApiPublicOutboundIpRoute
  ApiPublicChatConfigRoute: typeof ApiPublicChatConfigRoute
  ApiPublicChatMessageRoute: typeof ApiPublicChatMessageRoute
  ApiPublicChatStartRoute: typeof ApiPublicChatStartRoute
  ApiPublicJuwaBalanceRoute: typeof ApiPublicJuwaBalanceRoute
  ApiPublicJuwaCreatePlayerRoute: typeof ApiPublicJuwaCreatePlayerRoute
  ApiPublicJuwaRechargeRoute: typeof ApiPublicJuwaRechargeRoute
  ApiPublicJuwaResetPasswordRoute: typeof ApiPublicJuwaResetPasswordRoute
  ApiPublicJuwaWithdrawRoute: typeof ApiPublicJuwaWithdrawRoute
  ApiSupportAttachmentMessageIdRoute: typeof ApiSupportAttachmentMessageIdRoute
  ApiPublicChatTicketIdMessagesRoute: typeof ApiPublicChatTicketIdMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet-tools': {
      id: '/_authenticated/wallet-tools'
      path: '/wallet-tools'
      fullPath: '/wallet-tools'
      preLoaderRoute: typeof AuthenticatedWalletToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip': {
      id: '/_authenticated/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AuthenticatedVipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms-theme': {
      id: '/_authenticated/cms-theme'
      path: '/cms-theme'
      fullPath: '/cms-theme'
      preLoaderRoute: typeof AuthenticatedCmsThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms-music': {
      id: '/_authenticated/cms-music'
      path: '/cms-music'
      fullPath: '/cms-music'
      preLoaderRoute: typeof AuthenticatedCmsMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms-games': {
      id: '/_authenticated/cms-games'
      path: '/cms-games'
      fullPath: '/cms-games'
      preLoaderRoute: typeof AuthenticatedCmsGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashouts': {
      id: '/_authenticated/cashouts'
      path: '/cashouts'
      fullPath: '/cashouts'
      preLoaderRoute: typeof AuthenticatedCashoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/outbound-ip': {
      id: '/api/public/outbound-ip'
      path: '/api/public/outbound-ip'
      fullPath: '/api/public/outbound-ip'
      preLoaderRoute: typeof ApiPublicOutboundIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/webhook': {
      id: '/api/meta/webhook'
      path: '/api/meta/webhook'
      fullPath: '/api/meta/webhook'
      preLoaderRoute: typeof ApiMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support/attachment/$messageId': {
      id: '/api/support/attachment/$messageId'
      path: '/api/support/attachment/$messageId'
      fullPath: '/api/support/attachment/$messageId'
      preLoaderRoute: typeof ApiSupportAttachmentMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juwa/withdraw': {
      id: '/api/public/juwa/withdraw'
      path: '/api/public/juwa/withdraw'
      fullPath: '/api/public/juwa/withdraw'
      preLoaderRoute: typeof ApiPublicJuwaWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juwa/reset-password': {
      id: '/api/public/juwa/reset-password'
      path: '/api/public/juwa/reset-password'
      fullPath: '/api/public/juwa/reset-password'
      preLoaderRoute: typeof ApiPublicJuwaResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juwa/recharge': {
      id: '/api/public/juwa/recharge'
      path: '/api/public/juwa/recharge'
      fullPath: '/api/public/juwa/recharge'
      preLoaderRoute: typeof ApiPublicJuwaRechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juwa/create-player': {
      id: '/api/public/juwa/create-player'
      path: '/api/public/juwa/create-player'
      fullPath: '/api/public/juwa/create-player'
      preLoaderRoute: typeof ApiPublicJuwaCreatePlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juwa/balance': {
      id: '/api/public/juwa/balance'
      path: '/api/public/juwa/balance'
      fullPath: '/api/public/juwa/balance'
      preLoaderRoute: typeof ApiPublicJuwaBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/start': {
      id: '/api/public/chat/start'
      path: '/api/public/chat/start'
      fullPath: '/api/public/chat/start'
      preLoaderRoute: typeof ApiPublicChatStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/message': {
      id: '/api/public/chat/message'
      path: '/api/public/chat/message'
      fullPath: '/api/public/chat/message'
      preLoaderRoute: typeof ApiPublicChatMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/config': {
      id: '/api/public/chat/config'
      path: '/api/public/chat/config'
      fullPath: '/api/public/chat/config'
      preLoaderRoute: typeof ApiPublicChatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/ticket/$id/messages': {
      id: '/api/public/chat/ticket/$id/messages'
      path: '/api/public/chat/ticket/$id/messages'
      fullPath: '/api/public/chat/ticket/$id/messages'
      preLoaderRoute: typeof ApiPublicChatTicketIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedCashoutsRoute: typeof AuthenticatedCashoutsRoute
  AuthenticatedCmsGamesRoute: typeof AuthenticatedCmsGamesRoute
  AuthenticatedCmsMusicRoute: typeof AuthenticatedCmsMusicRoute
  AuthenticatedCmsThemeRoute: typeof AuthenticatedCmsThemeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedVipRoute: typeof AuthenticatedVipRoute
  AuthenticatedWalletToolsRoute: typeof AuthenticatedWalletToolsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedCashoutsRoute: AuthenticatedCashoutsRoute,
  AuthenticatedCmsGamesRoute: AuthenticatedCmsGamesRoute,
  AuthenticatedCmsMusicRoute: AuthenticatedCmsMusicRoute,
  AuthenticatedCmsThemeRoute: AuthenticatedCmsThemeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedVipRoute: AuthenticatedVipRoute,
  AuthenticatedWalletToolsRoute: AuthenticatedWalletToolsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMetaWebhookRoute: ApiMetaWebhookRoute,
  ApiPublicOutboundIpRoute: ApiPublicOutboundIpRoute,
  ApiPublicChatConfigRoute: ApiPublicChatConfigRoute,
  ApiPublicChatMessageRoute: ApiPublicChatMessageRoute,
  ApiPublicChatStartRoute: ApiPublicChatStartRoute,
  ApiPublicJuwaBalanceRoute: ApiPublicJuwaBalanceRoute,
  ApiPublicJuwaCreatePlayerRoute: ApiPublicJuwaCreatePlayerRoute,
  ApiPublicJuwaRechargeRoute: ApiPublicJuwaRechargeRoute,
  ApiPublicJuwaResetPasswordRoute: ApiPublicJuwaResetPasswordRoute,
  ApiPublicJuwaWithdrawRoute: ApiPublicJuwaWithdrawRoute,
  ApiSupportAttachmentMessageIdRoute: ApiSupportAttachmentMessageIdRoute,
  ApiPublicChatTicketIdMessagesRoute: ApiPublicChatTicketIdMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
