/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashoutsRouteImport } from './routes/_authenticated/cashouts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashoutsRoute = AuthenticatedCashoutsRouteImport.update({
  id: '/cashouts',
  path: '/cashouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashouts': typeof AuthenticatedCashoutsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashouts': typeof AuthenticatedCashoutsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cashouts': typeof AuthenticatedCashoutsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cashouts'
    | '/dashboard'
    | '/deposits'
    | '/payment-methods'
    | '/players'
    | '/reports'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cashouts'
    | '/dashboard'
    | '/deposits'
    | '/payment-methods'
    | '/players'
    | '/reports'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cashouts'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposits'
    | '/_authenticated/payment-methods'
    | '/_authenticated/players'
    | '/_authenticated/reports'
    | '/_authenticated/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashouts': {
      id: '/_authenticated/cashouts'
      path: '/cashouts'
      fullPath: '/cashouts'
      preLoaderRoute: typeof AuthenticatedCashoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashoutsRoute: typeof AuthenticatedCashoutsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashoutsRoute: AuthenticatedCashoutsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
